name: Update RTMA Data

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: geo-env
          create-args: >-
            python=3.9
            xarray
            cfgrib
            matplotlib
            scipy
            boto3
            eccodes
            numpy

      - name: Run Script
        shell: bash -l {0}
        run: |
          # Explicitly tell python where eccodes is (Fixes 'library not found' errors)
          export ECCODES_DEFINITION_PATH=$CONDA_PREFIX/share/eccodes/definitions
          
          # Run the script
          python process_rtma.py

      # Debugging: List files to ensure they exist before we try to deploy
      - name: Verify Output
        run: |
          echo "Checking site/data folder..."
          ls -R site/

      - name: Add .nojekyll
        run: touch site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
